---
name: 'Code Composer Studio Project Builder'
description: 'GitHub action to build a Code Composer Studio Project'
author: 'Grahame White'
inputs:
  project-path:
    description: ''
    required: true
    default: '/workdir'
  project-name:
    description: 'The CCS project file to build'
    required: true
    default: 'project'
  build-configuration:
    description: 'The build configuration to use when building'
    required: false
    default: 'Debug'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/grahame-student/ccs_build:v0.0.15-c'
  args:
    - ${{ inputs.project-path }}
    - ${{ inputs.project-name }}
    - ${{ inputs.build-configuration }}
branding:
  icon: 'code'
  colour: 'red'
