---
name: Test released ccs_build action

on:
  workflow_dispatch:
  
jobs:
  test_ccs_build:
    runs-on: ubuntu-latest
    name: Test CCS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CCS Build action step
        uses: grahame-student/ccs_build@v0.0.16
        with:
          build-configuration: Debug
