---
name: Test released ccs_build action

on:
  workflow_dispatch:
  
jobs:
  test_ccs_build:
    runs-on: ubuntu-latest
    name: Test CCS Build
    steps:
      - name: CCS Build action step
        uses: docker://grahame-student/ccs_build@v0.0.2
        with:
          project-name: test1
          build-configuration: test2
